### ISSUE TITLE
PWM flicker

### ISSUE THREAD

**Issue by Beherith** [DarkFox/LED_controller#1]
PWM on pins 5 and 6 runs asynchronously from the one on pins 9 and 10 (511 cycles vs 2x256=512, fast pwm vs phase correct pwm). This results in flicker. It is perfectly explained by someone else in this blog post, and the solution is offered as well:
add bitSet(TCCR1B, WGM12); to setup();

http://jeelabs.org/2011/11/08/fixing-the-arduinos-pwm
http://jeelabs.org/2011/11/09/fixing-the-arduinos-pwm-2/

Thanks for your shared code, it is excellent!

**Comment by DarkFox** [comment]
Awesome, thanks for letting me know. :-)

**Comment by Beherith** [comment]
Goddamn you are fast, much <3
