### ISSUE TITLE
Change Mode

### ISSUE THREAD

**Issue by rohinrohin** [DarkFox/LED_controller#3]
This is a Question, not an issue
I'm trying to port this to only work on IR Reciever mode, 
However, i just can't get the change mode function to work, to change the mode to strobe, or pulse, etc, etc. Any help is appreciated.

**Comment by DarkFox** [comment]
You press the menu button on the remote, then use the number buttons to select the mode you want.

The relevant code is at [L547-L553](https://github.com/DarkFox/LED_controller/blob/master/HSL_LED_controller_IR.c#L547-L553) and [L360-L462](https://github.com/DarkFox/LED_controller/blob/master/HSL_LED_controller_IR.c#L360-L462)
